# Generated by Django 4.0.6 on 2023-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('review_complete', 'Review Complete'), ('closed', 'Closed')], default='open', max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parts_used', models.TextField(blank=True, null=True)),
                ('work_completed', models.TextField(blank=True, null=True)),
                ('work_to_be_completed', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('work_time_start', models.TimeField(blank=True, null=True)),
                ('work_time_end', models.TimeField(blank=True, null=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('est_completion', models.TimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Is Emergency')),
            ],
        ),
    ]
